language: cpp

script:
        - cmake -H. -B_build -DBUILD_TESTS=ON
        - cmake --build _build
        - cmake --build _build --target test -- ARGS=--verbose
addons:
        apt:
                packages:
                        - cmake
                        - cmake-data

before_script:
        - composer install --dev
script: 
        - phpunit --coverage-clover build/logs/clover.xml
after_success:
        - php vendor/bin/coveralls -v
