language: cpp

script:
        - cmake -H. -B_build -DBUILD_TESTS=ON
        - cmake --build _build --target install
        - cmake --build _build --target test -- ARGS=--verbose
addons:
        apt:
                packages:
                        - cmake
                        - cmake-data

