language: cpp

script:
        - ./configure --enable-gcov
        - cmake -H. -B_build -DBUILD_TESTS=ON
        - cmake --build _build
        - cmake --build _build --target test -- ARGS=--verbose
addons:
        apt:
                packages:
                        - cmake
                        - cmake-data

before_script:
        - pip install --user cpp-coveralls
after_script:
        - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
